name: swift_control
description: "SwiftControl - Control your virtual riding"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 3.1.0+28

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.3.1
  flutter_local_notifications: ^19.4.1

  # fork to allow iOS background BLE connections
  universal_ble:
    git:
      url: https://github.com/jonasbark/universal_ble.git

  intl: any
  version: ^3.0.0
  bluetooth_low_energy: ^6.1.0
  wakelock_plus: ^1.4.0
  protobuf: ^4.2.0
  flutter_md: ^0.0.7
  permission_handler: ^12.0.1
  dartx: any
  image_picker: ^1.1.2
  window_manager: ^0.5.1
  device_info_plus: ^12.1.0
  keypress_simulator:
    path: keypress_simulator/packages/keypress_simulator
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  flex_color_scheme: ^8.3.0
  accessibility:
    path: accessibility

  # shorebird related
  shorebird_code_push: ^2.0.5
  restart_app:
    git:
      url: https://github.com/maple135790/restart_app.git
      ref: feature/resolve-all-open-issues
  package_info_plus: ^9.0.0
  in_app_update: ^4.2.5
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  msix: ^3.16.12

flutter:
  uses-material-design: true
  assets:
    - CHANGELOG.md
    - TROUBLESHOOTING.md
    - shorebird.yaml

msix_config:
  display_name: SwiftControl
  publisher_display_name: Jonas Bark
  identity_name: JonasBark.SwiftControl
  publisher: CN=EDA6D86E-3E52-4054-9F3A-4277AFCCB2C4
  store: true
  msix_version: 1.0.0.0
  logo_path: logo.jpg
  build_windows: false
  capabilities: internetClient,bluetooth,inputInjectionBrokered
